# Generated by Django 5.1.4 on 2026-02-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('dodo', 'Dodo'), ('crypto', 'Crypto')], max_length=16)),
                ('chain', models.CharField(blank=True, choices=[('base', 'Base'), ('polygon', 'Polygon'), ('arbitrum', 'Arbitrum'), ('solana', 'Solana')], max_length=16, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('dodo_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by_carbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.carbon')),
                ('requested_by_silicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.silicon')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='websites.website')),
            ],
            options={
                'db_table': 'payment_requests',
            },
        ),
    ]
