# Generated by Django 5.1.4 on 2026-02-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='chain',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('polygon', 'Polygon'), ('arbitrum', 'Arbitrum'), ('ethereum', 'Ethereum'), ('bsc', 'Bsc'), ('solana', 'Solana')], max_length=16, null=True),
        ),
    ]
