# Generated by Django 5.1.4 on 2026-02-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_silicon_is_trusted_verifier'),
        ('payments', '0002_alter_paymentrequest_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='detailed_report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='verified_by_silicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_verifications', to='accounts.silicon'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='chain',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('polygon', 'Polygon'), ('arbitrum', 'Arbitrum'), ('ethereum', 'Ethereum'), ('bsc', 'Bsc')], max_length=16, null=True),
        ),
    ]
