# Generated by Django 5.1.4 on 2026-02-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_silicon_is_trusted_verifier'),
        ('payments', '0003_paymentrequest_detailed_report_paymentrequest_email_and_more'),
        ('websites', '0004_websiteverification_detailed_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='max_verification_requests',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('served', 'Served')], default='pending', max_length=16)),
                ('detailed_report', models.TextField(blank=True, default='')),
                ('level_at_verification', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='payments.paymentrequest')),
                ('requested_by_carbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.carbon')),
                ('requested_by_silicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_verifications', to='accounts.silicon')),
                ('verified_by_silicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_verification_requests', to='accounts.silicon')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='websites.website')),
            ],
            options={
                'db_table': 'verification_requests',
            },
        ),
    ]
