# Generated by Django 5.1.4 on 2026-02-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentrequest_max_verification_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='detailed_report',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='served',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='verified_by_silicon',
        ),
    ]
