# Generated by Django 5.1.4 on 2026-02-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_paymentrequest_detailed_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='chain',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('polygon', 'Polygon'), ('arbitrum', 'Arbitrum'), ('ethereum', 'Ethereum'), ('bsc', 'Bsc'), ('avalanche', 'Avalanche')], max_length=16, null=True),
        ),
    ]
