# Generated by Django 5.1.4 on 2026-02-17 17:23

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_my_website', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('l1_semantic_html', models.BooleanField(default=False)),
                ('l1_meta_tags', models.BooleanField(default=False)),
                ('l1_schema_org', models.BooleanField(default=False)),
                ('l1_no_captcha', models.BooleanField(default=False)),
                ('l1_ssr_content', models.BooleanField(default=False)),
                ('l1_clean_urls', models.BooleanField(default=False)),
                ('l2_robots_txt', models.BooleanField(default=False)),
                ('l2_sitemap', models.BooleanField(default=False)),
                ('l2_llms_txt', models.BooleanField(default=False)),
                ('l2_openapi_spec', models.BooleanField(default=False)),
                ('l2_documentation', models.BooleanField(default=False)),
                ('l2_text_content', models.BooleanField(default=False)),
                ('l3_structured_api', models.BooleanField(default=False)),
                ('l3_json_responses', models.BooleanField(default=False)),
                ('l3_search_filter_api', models.BooleanField(default=False)),
                ('l3_a2a_agent_card', models.BooleanField(default=False)),
                ('l3_rate_limits_documented', models.BooleanField(default=False)),
                ('l3_structured_errors', models.BooleanField(default=False)),
                ('l4_mcp_server', models.BooleanField(default=False)),
                ('l4_webmcp', models.BooleanField(default=False)),
                ('l4_write_api', models.BooleanField(default=False)),
                ('l4_agent_auth', models.BooleanField(default=False)),
                ('l4_webhooks', models.BooleanField(default=False)),
                ('l4_idempotency', models.BooleanField(default=False)),
                ('l5_event_streaming', models.BooleanField(default=False)),
                ('l5_agent_negotiation', models.BooleanField(default=False)),
                ('l5_subscription_api', models.BooleanField(default=False)),
                ('l5_workflow_orchestration', models.BooleanField(default=False)),
                ('l5_proactive_notifications', models.BooleanField(default=False)),
                ('l5_cross_service_handoff', models.BooleanField(default=False)),
                ('submitted_by_carbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_websites', to='accounts.carbon')),
                ('submitted_by_silicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_websites', to='accounts.silicon')),
            ],
            options={
                'db_table': 'websites',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('websites', models.ManyToManyField(related_name='keywords', to='websites.website')),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='WebsiteVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trusted', models.BooleanField(default=False)),
                ('counted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('l1_semantic_html', models.BooleanField(default=False)),
                ('l1_meta_tags', models.BooleanField(default=False)),
                ('l1_schema_org', models.BooleanField(default=False)),
                ('l1_no_captcha', models.BooleanField(default=False)),
                ('l1_ssr_content', models.BooleanField(default=False)),
                ('l1_clean_urls', models.BooleanField(default=False)),
                ('l2_robots_txt', models.BooleanField(default=False)),
                ('l2_sitemap', models.BooleanField(default=False)),
                ('l2_llms_txt', models.BooleanField(default=False)),
                ('l2_openapi_spec', models.BooleanField(default=False)),
                ('l2_documentation', models.BooleanField(default=False)),
                ('l2_text_content', models.BooleanField(default=False)),
                ('l3_structured_api', models.BooleanField(default=False)),
                ('l3_json_responses', models.BooleanField(default=False)),
                ('l3_search_filter_api', models.BooleanField(default=False)),
                ('l3_a2a_agent_card', models.BooleanField(default=False)),
                ('l3_rate_limits_documented', models.BooleanField(default=False)),
                ('l3_structured_errors', models.BooleanField(default=False)),
                ('l4_mcp_server', models.BooleanField(default=False)),
                ('l4_webmcp', models.BooleanField(default=False)),
                ('l4_write_api', models.BooleanField(default=False)),
                ('l4_agent_auth', models.BooleanField(default=False)),
                ('l4_webhooks', models.BooleanField(default=False)),
                ('l4_idempotency', models.BooleanField(default=False)),
                ('l5_event_streaming', models.BooleanField(default=False)),
                ('l5_agent_negotiation', models.BooleanField(default=False)),
                ('l5_subscription_api', models.BooleanField(default=False)),
                ('l5_workflow_orchestration', models.BooleanField(default=False)),
                ('l5_proactive_notifications', models.BooleanField(default=False)),
                ('l5_cross_service_handoff', models.BooleanField(default=False)),
                ('verified_by_carbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.carbon')),
                ('verified_by_silicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.silicon')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='websites.website')),
            ],
            options={
                'db_table': 'website_verifications',
            },
        ),
        migrations.AddField(
            model_name='website',
            name='trusted_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='websites.websiteverification'),
        ),
        migrations.AddConstraint(
            model_name='websiteverification',
            constraint=models.UniqueConstraint(condition=models.Q(('verified_by_silicon__isnull', False)), fields=('website', 'verified_by_silicon'), name='uq_verification_silicon'),
        ),
        migrations.AddConstraint(
            model_name='websiteverification',
            constraint=models.UniqueConstraint(condition=models.Q(('verified_by_carbon__isnull', False)), fields=('website', 'verified_by_carbon'), name='uq_verification_carbon'),
        ),
    ]
