# Generated by Django 5.1.4 on 2026-02-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='entry_point',
            field=models.URLField(blank=True, default='', help_text='URL where an agent should start interacting with this site', max_length=500),
        ),
    ]
