# Generated by Django 5.1.4 on 2026-02-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_rename_entry_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteverification',
            name='detailed_report',
            field=models.TextField(blank=True, default=''),
        ),
    ]
