# Generated by Django 5.1.7 on 2026-03-20 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_carbon_google_auth_fields'),
        ('websites', '0004_websiteverification_detailed_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('website_name', models.CharField(blank=True, default='', max_length=255)),
                ('website_description', models.TextField(blank=True, default='')),
                ('level_1_results', models.JSONField(blank=True, null=True)),
                ('level_2_results', models.JSONField(blank=True, null=True)),
                ('level_3_results', models.JSONField(blank=True, null=True)),
                ('level_4_results', models.JSONField(blank=True, null=True)),
                ('level_5_results', models.JSONField(blank=True, null=True)),
                ('level_1_reasoning', models.JSONField(blank=True, null=True)),
                ('level_2_reasoning', models.JSONField(blank=True, null=True)),
                ('level_3_reasoning', models.JSONField(blank=True, null=True)),
                ('level_4_reasoning', models.JSONField(blank=True, null=True)),
                ('level_5_reasoning', models.JSONField(blank=True, null=True)),
                ('report_md', models.TextField(blank=True, default='')),
                ('overall_level', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carbon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.carbon')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.website')),
            ],
            options={
                'db_table': 'check_jobs',
            },
        ),
    ]
