# Generated by Django 5.1.7 on 2026-03-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_add_checkjob_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='page_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
