# Generated by Django 5.1.4 on 2026-02-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='silicon',
            name='is_trusted_verifier',
            field=models.BooleanField(default=False),
        ),
    ]
