# Generated by Django 5.1.7 on 2026-03-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_silicon_is_trusted_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbon',
            name='auth_provider',
            field=models.CharField(default='google', max_length=32),
        ),
        migrations.AddField(
            model_name='carbon',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='carbon',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
